OWNER_NAME="Denking"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "DEN-MD-BOT"
IMAGE_MENU= "https://telegra.ph/file/557f1309a0005c937db7e.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛Denking᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'

